routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\TeacherController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect('/home');
})->name('root');

Route::get('/home', [HomeController::class, 'index'])->name('dashboard');
//teacher
Route::prefix('teacher')->name('teacher.')->group(function () {
    Route::get('/show', [TeacherController::class, 'show'])->name('show');
    Route::get('/add', [TeacherController::class, 'add'])->name('add');
    Route::get('/store/{id}', [TeacherController::class, 'store'])->name('store');
});

//course
Route::prefix('courses')->name('course.')->group(function () {
    Route::get('/add', [CourseController::class, 'add'])->name('add');
    Route::post('/add', [CourseController::class, 'create'])->name('create');

    Route::get('/edit', [CourseController::class, 'edit'])->name('edit');
    Route::post('/edit', [CourseController::class, 'update'])->name('update');
});

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'description',
        'image',
    ];

    public function course_roles()
    {
        return $this->hasMany(CourseRole::class, 'course_id', 'id');
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Models/CourseRole.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CourseRole extends Model
{
    use HasFactory;
    protected $fillable = [
        'user_id',
        'course_id',
        'role',
    ];
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function course()
    {
        return $this->belongsTo(Course::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'email_verified_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function course_roles()
    {
        return $this->hasMany(CourseRole::class, 'user_id', 'id');
    }

    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }
}

app/Http/Controllers/Admin/CourseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DTO\CreateCourseDto;
use App\Http\Controllers\Controller;
use App\Http\Requests\CourseRequestCreate;
use App\Repositories\TeacherRepository;
use App\Repositories\UserRepository;
use App\Services\admin\CourseService;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    private $teacherRepository;
    public function __construct(TeacherRepository $teacherRepository)
    {
        $this->middleware(['auth', 'role:admin']);
        $this->teacherRepository = $teacherRepository;
    }

    public function add()
    {
        $teachers = $this->teacherRepository->get();
        return view('pages.courses.add', compact('teachers'));
    }

    public function create(CourseRequestCreate $req)
    {
        $image_url = null;
        $req->image != null ?
            $image_url = $req->file('image')->store('images', 'private') :
            $image_url = null;

        $createCourse = new CreateCourseDto($req->name, $req->description, $image_url, $req->teacher_id);
        CourseService::create($createCourse);
        return redirect()->route('course.add')->with('success', __('translation.add_success'));
    }

    public function edit()
    {
    }

    public function update()
    {
    }
}

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Repositories\UserRepository;
use App\Services\AppService;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    private $userRepository;
    public function __construct(UserRepository $userRepository)
    {
        $this->middleware(['auth', 'role:admin']);
        $this->userRepository = $userRepository;
    }

    public function add(Request $req)
    {
        $users = $this->userRepository->searchFilter()->query()->paginate(env('paginate'));

        return view('pages.teachers.add', compact('users'));
    }
    public function store($id)
    {
        AppService::changeRole('teacher', $id);
        return redirect()->route('teacher.add')->with('success', __('translation.add_success'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    //Start
    public function __construct()
    {
        $this->middleware(['auth',  'verified']);
    }

    //Home page data - users
    public function index(Request $request){
        return view('dashboard');
    }
}

resources/views/dashboard.blade.php
@extends('layouts.master')

@section('title')
    @lang('translation.dashboard.name')
@endsection

@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            @lang('translation.dashboard.name')
        @endslot
        @slot('title')
            @lang('translation.dashboard.name')
        @endslot
    @endcomponent

    <div class="row">
        <div class="col-xl-4">
            <div class="card overflow-hidden">
                <div class="bg-primary bg-soft">
                    <div class="row">
                        <div class="col-7">
                            <div class="text-primary p-3">
                                <h5 class="text-primary">@lang('translation.dashboard.welcome')</h5>
                                <p>@lang('translation.dashboard.short') </p>
                            </div>
                        </div>
                        <div class="col-5 align-self-end">
                            {{-- <img src="{{ URL::asset('/build/images/profile-img.png') }}" alt="" class="img-fluid"> --}}
                        </div>
                    </div>
                </div>
                <div class="card-body pt-0">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="avatar-md profile-user-wid mb-4">
                                <img src="{{ isset(Auth::user()->avatar) ? asset(Auth::user()->avatar) : asset('/build/images/users/1689045779.png') }}"
                                    alt="" class="img-thumbnail rounded-circle">
                            </div>
                            <h5 class="font-size-15 text-truncate">
                                {{ Str::ucfirst(Auth::user()->first_name . ' ' . Auth::user()->last_name) }}</h5>
                            <!--  <p class="text-muted mb-0 text-truncate">UI/UX Designer</p>-->
                        </div>

                        <div class="col-sm-8">
                            <div class="pt-4">
                                <div class="row">
                                    <div class="col-6">
                                        <h5 class="font-size-15">0</h5>
                                        <p class="text-muted mb-0">@lang('translation.dashboard.order')</p>
                                    </div>
                                    <div class="col-6">
                                        <h5 class="font-size-15">0</h5>
                                        <p class="text-muted mb-0">@lang('translation.dashboard.revenue')</p>
                                    </div>
                                </div>
                                <div class="mt-4">
                                    <a href=""
                                        class="btn btn-primary waves-effect waves-light btn-sm float-end">@lang('translation.Profile')
                                        <i class="mdi mdi-arrow-right ms-1"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {{-- @foreach ($semesters as $semester)
            <div class="col-xl-3 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="fs-17 mb-2">{{ $semester->name }}</h5>
                        <h6 class="fs-17 mb-2">{{ $semester->program->name }} ({{ $semester->programYear->year }})</h4>
                        <p class="fs-17 mb-2">{{ $semester->short_desc }}</p>
                        <ul class="d-flex flex-column list-inline mb-0" style="font-size: 14px;">
                            <li class="list-inline-item">
                                <p class="text-muted fs-16 mb-0"><i class="mdi mdi-credit-card"></i>
                                    <b>@lang('translation.price'):</b> {{ $semester->price }} @lang('translation.sar')
                                </p>
                            </li>
                            @if ($semester->first_payment != $semester->price)
                            <li class="list-inline-item">
                                <p class="text-muted fs-16 mb-0"><i class="mdi mdi-credit-card-check"></i>
                                    <b>@lang('translation.first_payment'):</b> {{ $semester->first_payment }} @lang('translation.sar')
                                </p>
                            </li>
                            @endif
                            <li class="list-inline-item">
                                <p class="text-muted fs-16 mb-1"><i class="mdi mdi-calendar-start"></i>
                                    <b>@lang('translation.date_start'):</b> {{ $semester->date_start }}
                                </p>
                            </li>
                            <li class="list-inline-item">
                                <p class="text-muted fs-16 mb-0"><i class="mdi mdi-calendar-end"></i>
                                    <b>@lang('translation.date_end'):</b> {{ $semester->date_end }}
                                </p>
                            </li>
                        </ul>
                        <div class="mt-3 hstack gap-2">
                            <span class="badge rounded-1 badge-soft-warning"><i class="mdi mdi-account"></i>
                                {{ $semester->capacity }}</span>
                        </div>
                        <div class="mt-4 hstack gap-2">
                            <a href="{{ route('courses', $semester->id) }}" class="btn btn-secondary w-100">
                                @lang('translation.program.enter')
                            </a>
                            <a  href="#" data-bs-toggle="modal" data-bs-target="#myModal{{ $semester->id }}" class="btn btn-warning w-100">@lang('translation.courses_chk')</a>
                            <!-- sample modal content -->
                            <div id="myModal{{ $semester->id }}" class="modal fade" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="myModalLabel">@lang('translation.courses_chk')</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <h5>@lang('translation.courses')</h5>
                                            <p>
                                            @foreach ( $semester->courses as $course )
                                                <strong> @lang('translation.course_name') </strong> : {{ $course->name }}
                                                <br>
                                                {{ $course->short_desc }}
                                                <br>
                                                <strong> @lang('translation.trainer') </strong> : {{ $course->user->first_name }} {{ $course->user->last_name }}
                                                <br>
                                                <strong> @lang('translation.full_point') </strong> : {{ $course->full_point }}
                                                <strong> @lang('translation.fail_point') </strong> : {{ $course->fail_point }}
                                                <strong> @lang('translation.permanency_require') </strong> : {{ $course->permanency_require ? trans('translation.yes') : trans('translation.no')  }}
                                                <br><br>
                                            @endforeach
                                            </p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary waves-effect" data-bs-dismiss="modal">@lang('translation.close')</button>
                                        </div>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal-dialog -->
                            </div><!-- /.modal -->
                        </div>
                    </div>
                </div>
            </div>
        @endforeach --}}
    </div>
    <!-- end row -->

@endsection
@section('script')
    <!-- apexcharts -->
    <script src="{{ URL::asset('/build/libs/apexcharts/apexcharts.min.js') }}"></script>

    <!-- dashboard init -->
    <script src="{{ URL::asset('build/js/pages/dashboard.init.js') }}"></script>
@endsection

resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <p class="mb-0">© <script>
                    document.write(new Date().getFullYear())
                </script> @lang('translation.copyright2')</p>
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    <p class="mb-0"> @lang('translation.copyright3') <i class="mdi mdi-heart text-danger"></i> @lang('translation.by')
                    <a target="_blank" href="https://yashamturk.com/">@lang('translation.yasham')</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans text-gray-900 antialiased">
        <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
            <div>
                <a href="/">
                    <x-application-logo class="w-20 h-20 fill-current text-gray-500" />
                </a>
            </div>

            <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
                {{ $slot }}
            </div>
        </div>
    </body>
</html>

resources/views/layouts/head-css.blade.php
@yield('css')

<!-- Bootstrap Css -->
<link href="{{ URL::asset('/build/css/bootstrap'.''.'.min.css') }}" id="bootstrap-style" rel="stylesheet" type="text/css" />
<!-- Icons Css -->
<link href="{{ URL::asset('/build/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
<!-- App Css-->
<link href="{{ URL::asset('/build/css/app'.''.'.min.css') }}" id="app-style" rel="stylesheet" type="text/css" />
<!-- App Css-->
<link href="{{ URL::asset('/custom/style.css') }}" rel="stylesheet" type="text/css" />

resources/views/layouts/master-layouts.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8" />
    <title> @yield('title') | Skote - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{{ URL::asset('build/images/favicon.ico') }}">
    @include('layouts.head-css')
</head>

@section('body')
    <body data-topbar="dark" data-layout="horizontal">
@show

    <!-- Begin page -->
    <div id="layout-wrapper">
        @include('layouts.horizontal')
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">
            <div class="page-content">
                <!-- Start content -->
                <div class="container-fluid">
                    @yield('content')
                </div> <!-- content -->
            </div>
            @include('layouts.footer')
        </div>
        <!-- ============================================================== -->
        <!-- End Right content here -->
        <!-- ============================================================== -->
    </div>
    <!-- END wrapper -->

    <!-- Right Sidebar -->
    @include('layouts.right-sidebar')
    <!-- END Right Sidebar -->

    @include('layouts.vendor-scripts')
</body>

</html>

resources/views/layouts/master-without-nav.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" style=" direction:@lang('interface.dir') !important">

    <head>
        <meta charset="utf-8" />
        <title> @yield('title') @lang('translation.app_title')</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta content="@lang('translation.app_description')" name="description" />
        <meta content="@lang('translation.app_author')" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{{ URL::asset('build/images/favicon.ico')}}">
        @include('layouts.head-css')
  </head>
    <body dir="@lang('interface.dir')">
    @yield('body')

    @yield('content')

    @include('layouts.vendor-scripts')
    </body>
</html>

resources/views/layouts/sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">
    <div data-simplebar class="h-100">
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <!--<li class="menu-title" key="t-menu">@lang('translation.Menu')</li>-->

                <li>
                    <a href="/dashboard" class="waves-effect" key="t-default">
                        <i class="bx bx-home-circle"></i>
                        <span key="t-dashboards">@lang('translation.dashboard.name')</span>
                    </a>

                </li>
                @can('user_info')
                    <li class="">
                        <a href="javascript: void(0);" class="has-arrow waves-effect" aria-expanded="false">
                            <i class="bx bx-user-circle"></i>
                            <span key="t-blog">@lang('translation.users')</span>
                        </a>
                        <ul class="sub-menu mm-collapse" aria-expanded="false" style="height: 0px;">

                            <li><a href="{{ route('users.index') }}" key="t-users-add">
                                    @lang('translation.managersusers')</a>
                            </li>
                            <li><a href="{{ route('users.trainee') }}" key="t-users-add">
                                    @lang('translation.alltrainee')</a>
                            </li>
                            {{-- <li><a href="{{ route('users.create') }}" key="t-users-add">
                                    @lang('translation.user_create')</a>
                            </li> --}}

                        </ul>
                    </li>
                @endcan

                @can('payments')
                    <li class="">
                        <a href="javascript: void(0);" class="has-arrow waves-effect" aria-expanded="false">
                            <i class="bx bx-dollar"></i>
                            <span key="t-blog">@lang('translation.Bills')</span>
                        </a>
                        <ul class="sub-menu mm-collapse" aria-expanded="false" style="height: 0px;">
                            <li><a href="{{ route('bills') }}" key="t-users-add">
                                    @lang('translation.AllBills')</a>
                            </li>
                        </ul>
                    </li>
                @endcan



                @if (Auth::check() && Auth::user()->hasRole('admin'))
                    <li class="">
                        <a href="javascript: void(0);" class="has-arrow waves-effect" aria-expanded="false">
                            <i class="bx bx-book-open"></i>
                            <span key="t-blog">@lang('translation.teacher.manage')</span>
                        </a>

                        <ul class="sub-menu mm-collapse" aria-expanded="false" style="height: 0px;">
                            <li><a href="{{ route('teacher.add') }}" key="t-users-add">
                                    @lang('translation.teacher.add')</a>
                            </li>
                            <li><a href="" key="t-users-add">
                                    @lang('translation.teacher.show')</a>
                            </li>

                        </ul>
                    </li>
                @endif

                @if (Auth::check() && Auth::user()->hasRole('admin'))
                    <li class="">
                        <a href="javascript: void(0);" class="has-arrow waves-effect" aria-expanded="false">
                            <i class="bx bx-book-open"></i>
                            <span key="t-blog">@lang('translation.course.manage')</span>
                        </a>

                        <ul class="sub-menu mm-collapse" aria-expanded="false" style="height: 0px;">
                            <li><a href="{{ route('course.add') }}" key="t-users-add">
                                    @lang('translation.course.add')</a>
                            </li>
                            <li><a href="{{ route('course.edit') }}" key="t-users-add">
                                    @lang('translation.course.edit')</a>
                            </li>

                        </ul>
                    </li>
                @endif
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

resources/views/pages/teachers/add.blade.php
@extends('layouts.master')

@section('title')
    @lang('translation.users')
@endsection
@section('css')
    <!-- bootstrap-datepicker css -->
    <link href="{{ URL::asset('build/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}" rel="stylesheet"
        type="text/css">

    <!-- DataTables -->
    <link href="{{ URL::asset('build/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{{ URL::asset('build/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}"
        rel="stylesheet" type="text/css" />
@endsection
@section('content')
    @component('components.alert')
    @endcomponent

    <div class="row">

        <h1> @lang('translation.user.all') </h1>
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-sm-12">
                            <form method="GET" action="" class="d-flex" style="justify-content: space-between;">
                                <div class="mb-2 search-box col-sm-2">
                                    <div class="position-relative">
                                        <input type="text" class="form-control" id="search" name="search"
                                            placeholder="@lang('translation.search')" value="{{ Request::get('search') }}">
                                        <i class="bx bx-search-alt search-icon"></i>
                                    </div>
                                </div>

                            </form>
                        </div>
                        <!-- end col-->
                    </div>
                    <div class="table-responsive">
                        <table class="table align-middle table-nowrap dt-responsive nowrap w-100" id="productsList-table">
                            <thead class="table-light">
                                <tr>
                                    <th class="col-1">@lang('translation.id')</th>
                                    <th class="col-2">@lang('translation.user.name')</th>
                                    <th class="col-2">@lang('translation.user.email')</th>
                                    <th class="col-3">@lang('translation.action.name')</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td>{{ $user->id }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>
                                            <div class="d-flex gap-3">
                                                <a href="{{ route('teacher.store', $user->id) }}"
                                                    class="btn btn-light btn-rounded waves-effect">
                                                    <i class="mdi mdi-account-plus font-size-14"></i>
                                                    @lang('translation.action.addTeacher')
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <!-- end table -->
                    </div>
                    {!! $users->links('components.pagination') !!}
                    <!-- end table responsive -->
                </div>
                <!-- end card body -->
            </div>
            <!-- end card -->
        </div>
        <!-- end col -->
    </div>
    <!-- end row -->
@endsection

@section('script')
    <!-- bootstrap-datepicker js -->
    <script src="{{ URL::asset('build/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>

    <!-- Required datatable js -->
    <script src="{{ URL::asset('build/libs/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('build/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Responsive examples -->
    <script src="{{ URL::asset('build/libs/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ URL::asset('build/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>

    <!-- ecommerce-customer-list init
                                                                                                                                                                                                                        <script src="{{ URL::asset('build/js/pages/ecommerce-customer-list.init.js') }}"></script>-->
@endsection